# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/display/display.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display || ORIG_REF_NAME==display}]

# IP: bd/display/ip/display_calculator_0_0/display_calculator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_calculator_0_0 || ORIG_REF_NAME==display_calculator_0_0}]

# IP: bd/display/ip/display_BCD2SEG7_0_0/display_BCD2SEG7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_BCD2SEG7_0_0 || ORIG_REF_NAME==display_BCD2SEG7_0_0}]

# IP: bd/display/ip/display_xlconstant_0_0/display_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xlconstant_0_0 || ORIG_REF_NAME==display_xlconstant_0_0}]

# IP: bd/display/ip/display_xup_inv_0_0/display_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_0_0 || ORIG_REF_NAME==display_xup_inv_0_0}]

# IP: bd/display/ip/display_xup_inv_1_0/display_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_1_0 || ORIG_REF_NAME==display_xup_inv_1_0}]

# IP: bd/display/ip/display_xup_inv_2_0/display_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_2_0 || ORIG_REF_NAME==display_xup_inv_2_0}]

# IP: bd/display/ip/display_xup_inv_3_0/display_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_3_0 || ORIG_REF_NAME==display_xup_inv_3_0}]

# IP: bd/display/ip/display_xup_inv_4_0/display_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_4_0 || ORIG_REF_NAME==display_xup_inv_4_0}]

# IP: bd/display/ip/display_xup_inv_5_0/display_xup_inv_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_5_0 || ORIG_REF_NAME==display_xup_inv_5_0}]

# IP: bd/display/ip/display_xup_inv_6_0/display_xup_inv_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_xup_inv_6_0 || ORIG_REF_NAME==display_xup_inv_6_0}]

# XDC: bd/display/display_ooc.xdc
