# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ports.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top}]

# IP: bd/top/ip/top_calculator_0_0_1/top_calculator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_calculator_0_0 || ORIG_REF_NAME==top_calculator_0_0}]

# IP: bd/top/ip/top_xup_4_to_1_mux_vector_0_0_1/top_xup_4_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_4_to_1_mux_vector_0_0 || ORIG_REF_NAME==top_xup_4_to_1_mux_vector_0_0}]

# IP: bd/top/ip/top_xlconcat_0_0/top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_0_0 || ORIG_REF_NAME==top_xlconcat_0_0}]

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0}]

# IP: bd/top/ip/top_xlconcat_1_0/top_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_1_0 || ORIG_REF_NAME==top_xlconcat_1_0}]

# IP: bd/top/ip/top_xlconcat_2_0/top_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_2_0 || ORIG_REF_NAME==top_xlconcat_2_0}]

# IP: bd/top/ip/top_xlconstant_1_1/top_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_1_1 || ORIG_REF_NAME==top_xlconstant_1_1}]

# IP: bd/top/ip/top_xlconcat_0_1/top_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_0_1 || ORIG_REF_NAME==top_xlconcat_0_1}]

# IP: bd/top/ip/top_c_counter_binary_0_0/top_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_c_counter_binary_0_0 || ORIG_REF_NAME==top_c_counter_binary_0_0}]

# IP: bd/top/ip/top_xup_clk_divider_0_0_1/top_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_clk_divider_0_0 || ORIG_REF_NAME==top_xup_clk_divider_0_0}]

# IP: bd/top/ip/top_two_four_decoder_0_0/top_two_four_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_two_four_decoder_0_0 || ORIG_REF_NAME==top_two_four_decoder_0_0}]

# IP: bd/top/ip/top_xup_inv_0_0/top_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_inv_0_0 || ORIG_REF_NAME==top_xup_inv_0_0}]

# IP: bd/top/ip/top_xup_inv_1_0/top_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_inv_1_0 || ORIG_REF_NAME==top_xup_inv_1_0}]

# IP: bd/top/ip/top_xup_inv_2_0/top_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_inv_2_0 || ORIG_REF_NAME==top_xup_inv_2_0}]

# IP: bd/top/ip/top_xup_inv_3_0/top_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xup_inv_3_0 || ORIG_REF_NAME==top_xup_inv_3_0}]

# XDC: bd/top/top_ooc.xdc
