# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/peter/adder/adder.cache/wt [current_project]
set_property parent.project_path C:/Users/peter/adder/adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/peter/adder/ip_two_four_decoder
  c:/Users/peter/adder/ip_calculator
  c:/Users/peter/adder/ip_complement
  c:/Users/peter/mux21/74LSXX_LIB
  c:/Users/peter/adder/ip_full_adder_1_bit
  c:/Users/peter/adder/ip_full_adder_4_bit
  c:/Users/peter/mux21/XUP_LIB
} [current_project]
set_property ip_output_repo c:/Users/peter/adder/adder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/peter/adder/adder.srcs/sources_1/new/seven_seg.v
  C:/Users/peter/adder/adder.srcs/sources_1/new/top_ver.v
  C:/Users/peter/adder/adder.srcs/sources_1/new/top_display.v
}
add_files C:/Users/peter/adder/adder.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_0_0/src/complement_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_1_0/src/complement_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_complement_2_0/src/complement_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_calculator_0_0_1/src/calculator_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_c_counter_binary_0_0/top_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/peter/adder/adder.srcs/sources_1/bd/top/top_ooc.xdc]
set_property is_locked true [get_files C:/Users/peter/adder/adder.srcs/sources_1/bd/top/top.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/peter/adder/adder.srcs/constrs_2/new/ports.xdc
set_property used_in_implementation false [get_files C:/Users/peter/adder/adder.srcs/constrs_2/new/ports.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_display -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_display.dcp

catch { report_utilization -file top_display_utilization_synth.rpt -pb top_display_utilization_synth.pb }
