# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/top_two_four_decoder_0_0.xci
# IP: The module: 'top_two_four_decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xlslice_0_0/two_four_decoder_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xlslice_0_0 || ORIG_REF_NAME==two_four_decoder_xlslice_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xlslice_1_0/two_four_decoder_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xlslice_1_0 || ORIG_REF_NAME==two_four_decoder_xlslice_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_inv_0_0/two_four_decoder_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_inv_0_0 || ORIG_REF_NAME==two_four_decoder_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_inv_1_0/two_four_decoder_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_inv_1_0 || ORIG_REF_NAME==two_four_decoder_xup_inv_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_0/two_four_decoder_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_0 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_1_0/two_four_decoder_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_1_0 || ORIG_REF_NAME==two_four_decoder_xup_and2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_1/two_four_decoder_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_1 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_1}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_2/two_four_decoder_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_2 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_2}]

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_two_four_decoder_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/top_two_four_decoder_0_0.xci
# IP: The module: 'top_two_four_decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xlslice_0_0/two_four_decoder_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xlslice_0_0 || ORIG_REF_NAME==two_four_decoder_xlslice_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xlslice_1_0/two_four_decoder_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xlslice_1_0 || ORIG_REF_NAME==two_four_decoder_xlslice_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_inv_0_0/two_four_decoder_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_inv_0_0 || ORIG_REF_NAME==two_four_decoder_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_inv_1_0/two_four_decoder_xup_inv_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_inv_1_0 || ORIG_REF_NAME==two_four_decoder_xup_inv_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_0/two_four_decoder_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_0 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_1_0/two_four_decoder_xup_and2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_1_0 || ORIG_REF_NAME==two_four_decoder_xup_and2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_1/two_four_decoder_xup_and2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_1 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_1}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_xup_and2_0_2/two_four_decoder_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_four_decoder_xup_and2_0_2 || ORIG_REF_NAME==two_four_decoder_xup_and2_0_2}]

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/top/ip/top_two_four_decoder_0_0/src/two_four_decoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_two_four_decoder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
