# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/complement_full_adder_4_bit_0_0.xci
# IP: The module: 'complement_full_adder_4_bit_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/full_adder_4_bit_full_adder_1_bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_0 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/full_adder_4_bit_full_adder_1_bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_1 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_1}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/full_adder_4_bit_full_adder_1_bit_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_2 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_2}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/full_adder_4_bit_full_adder_1_bit_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_3 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_3}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complement_full_adder_4_bit_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/complement_full_adder_4_bit_0_0.xci
# IP: The module: 'complement_full_adder_4_bit_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/full_adder_4_bit_full_adder_1_bit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_0 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/full_adder_4_bit_full_adder_1_bit_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_1 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_1}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/full_adder_4_bit_full_adder_1_bit_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_2 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_2}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/full_adder_4_bit_full_adder_1_bit_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4_bit_full_adder_1_bit_0_3 || ORIG_REF_NAME==full_adder_4_bit_full_adder_1_bit_0_3}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_xor2_0_0/full_adder_1_bit_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xor2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_0_0/full_adder_1_bit_xup_nand2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_1_0/full_adder_1_bit_xup_nand2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_1_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_1_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_nand2_2_0/full_adder_1_bit_xup_nand2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_nand2_2_0 || ORIG_REF_NAME==full_adder_1_bit_xup_nand2_2_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_inv_0_0/full_adder_1_bit_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_inv_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_inv_0_0}]

# IP: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_xup_xnor2_0_0/full_adder_1_bit_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_1_bit_xup_xnor2_0_0 || ORIG_REF_NAME==full_adder_1_bit_xup_xnor2_0_0}]

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_0/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_1/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_2/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_full_adder_1_bit_0_3/src/full_adder_1_bit_ooc.xdc

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/complement/ip/complement_full_adder_4_bit_0_0/src/full_adder_4_bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complement_full_adder_4_bit_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
