# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/peter/adder/adder.srcs/sources_1/bd/display/ip/display_calculator_0_0_1/display_calculator_0_0.xci
# IP: The module: 'display_calculator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/display/ip/display_calculator_0_0_1/src/calculator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_calculator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/peter/adder/adder.srcs/sources_1/bd/display/ip/display_calculator_0_0_1/display_calculator_0_0.xci
# IP: The module: 'display_calculator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/peter/adder/adder.srcs/sources_1/bd/display/ip/display_calculator_0_0_1/src/calculator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_calculator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
